# Generated by Django 5.2.4 on 2025-07-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='acceso_total',
            field=models.BooleanField(default=False, help_text='Permite acceso total al sistema'),
        ),
    ]
