# Generated by Django 5.2.4 on 2025-07-26 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_adminprofile_acceso_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreColegio', models.CharField(max_length=200)),
                ('DireccionColegio', models.CharField(max_length=300)),
                ('TelefonoInstitucional', models.CharField(max_length=30)),
                ('CorreoInstitucional', models.EmailField(max_length=254)),
                ('NombresRepresentante', models.CharField(max_length=200)),
                ('TelefonoRepresentante', models.CharField(max_length=30)),
                ('CorreoRepresentante', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='participantes',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='participantes',
            name='grupos',
        ),
        migrations.RemoveField(
            model_name='participantes',
            name='nombres',
        ),
        migrations.AddField(
            model_name='grupoparticipantes',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='grupos', to='quizzes.participantes'),
        ),
        migrations.AddField(
            model_name='participantes',
            name='NombresCompletos',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupoparticipantes',
            name='representante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos', to='quizzes.representante'),
        ),
    ]
