# Generated by Django 5.2.4 on 2025-07-28 06:36

import quizzes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_representante_remove_participantes_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'verbose_name': 'Evaluación', 'verbose_name_plural': 'Evaluaciones'},
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='end_time',
            field=models.DateTimeField(default='2025-07-28 08:55', help_text='Fecha y hora de finalización de la ventana de acceso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='duration_minutes',
            field=models.PositiveIntegerField(help_text='Tiempo disponible para completar la evaluación (en minutos)'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='start_time',
            field=models.DateTimeField(help_text='Fecha y hora de inicio de la ventana de acceso'),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='cedula',
            field=models.CharField(max_length=10, unique=True, validators=[quizzes.models.validate_cedula]),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='phone',
            field=models.CharField(blank=True, max_length=10, validators=[quizzes.models.validate_phone]),
        ),
        migrations.AlterField(
            model_name='representante',
            name='TelefonoInstitucional',
            field=models.CharField(max_length=10, validators=[quizzes.models.validate_phone]),
        ),
        migrations.AlterField(
            model_name='representante',
            name='TelefonoRepresentante',
            field=models.CharField(max_length=10, validators=[quizzes.models.validate_phone]),
        ),
    ]
