# Generated by Django 5.2.4 on 2025-07-28 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_alter_evaluacion_options_evaluacion_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='etapa',
            field=models.IntegerField(choices=[(1, 'Etapa 1 - Clasificatoria'), (2, 'Etapa 2 - Semifinal'), (3, 'Etapa 3 - Final')], default=1, help_text='Etapa de la olimpiada'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='grupos_participantes',
            field=models.ManyToManyField(blank=True, related_name='evaluaciones_etapa1', to='quizzes.grupoparticipantes'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='participantes_individuales',
            field=models.ManyToManyField(blank=True, related_name='evaluaciones_individuales', to='quizzes.participantes'),
        ),
        migrations.CreateModel(
            name='ResultadoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tiempo_utilizado', models.PositiveIntegerField(default=0, help_text='Tiempo utilizado en minutos')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('completada', models.BooleanField(default=False)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='quizzes.evaluacion')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='quizzes.participantes')),
            ],
            options={
                'ordering': ['-puntaje', 'tiempo_utilizado'],
                'unique_together': {('evaluacion', 'participante')},
            },
        ),
    ]
