# Generated by Django 5.2.4 on 2025-07-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_evaluacion_etapa_evaluacion_grupos_participantes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='preguntas_a_mostrar',
            field=models.PositiveIntegerField(default=10, help_text='Número de preguntas que se mostrarán al estudiante (selección aleatoria)'),
        ),
        migrations.AddField(
            model_name='resultadoevaluacion',
            name='respuestas_guardadas',
            field=models.JSONField(blank=True, default=dict, help_text='Respuestas guardadas automáticamente'),
        ),
        migrations.AddField(
            model_name='resultadoevaluacion',
            name='tiempo_restante',
            field=models.PositiveIntegerField(default=0, help_text='Tiempo restante en segundos'),
        ),
        migrations.AddField(
            model_name='resultadoevaluacion',
            name='ultima_actividad',
            field=models.DateTimeField(auto_now=True, help_text='Última actividad del estudiante'),
        ),
    ]
