# Generated by Django 5.2.4 on 2025-07-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_evaluacion_preguntas_a_mostrar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='puntos',
            field=models.PositiveIntegerField(default=1, help_text='Puntos que vale esta pregunta'),
        ),
    ]
