# Generated by Django 5.2.4 on 2025-07-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_pregunta_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoevaluacion',
            name='puntos_obtenidos',
            field=models.PositiveIntegerField(default=0, help_text='Puntos obtenidos por el estudiante'),
        ),
        migrations.AddField(
            model_name='resultadoevaluacion',
            name='puntos_totales',
            field=models.PositiveIntegerField(default=0, help_text='Puntos totales de la evaluación'),
        ),
    ]
