# Generated by Django 5.2.4 on 2025-07-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_resultadoevaluacion_puntos_obtenidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantes',
            name='password_temporal',
            field=models.CharField(blank=True, help_text='Contraseña temporal para mostrar en correos', max_length=50),
        ),
    ]
