# Generated by Django 5.2.4 on 2025-07-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_participantes_password_temporal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadoevaluacion',
            name='puntos_obtenidos',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Puntos obtenidos por el estudiante (ponderado sobre 10)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='resultadoevaluacion',
            name='puntos_totales',
            field=models.PositiveIntegerField(default=10, help_text='Puntos totales de la evaluación (siempre 10)'),
        ),
    ]
