# Generated by Django 5.2.4 on 2025-07-31 11:31

import django.db.models.deletion
import quizzes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_alter_resultadoevaluacion_puntos_obtenidos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, help_text='Foto de perfil del usuario', null=True, upload_to='fotos/perfil/')),
                ('phone', models.CharField(blank=True, help_text='Teléfono del usuario', max_length=10, validators=[quizzes.models.validate_phone])),
                ('bio', models.TextField(blank=True, help_text='Biografía o descripción del usuario', max_length=500)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización del perfil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
