# Generated by Django 5.2.4 on 2025-08-01 08:31

import quizzes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0011_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Foto de perfil del usuario', null=True, upload_to=quizzes.models.upload_to_avatar),
        ),
    ]
