# Generated by Django 5.2.4 on 2025-08-01 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0012_alter_userprofile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoreoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado'), ('suspendido', 'Suspendido')], default='activo', max_length=20)),
                ('ultima_actividad', models.DateTimeField(auto_now=True)),
                ('tiempo_activo', models.PositiveIntegerField(default=0, help_text='Tiempo activo en segundos')),
                ('tiempo_inactivo', models.PositiveIntegerField(default=0, help_text='Tiempo inactivo en segundos')),
                ('pagina_actual', models.PositiveIntegerField(default=1, help_text='Página actual del estudiante')),
                ('preguntas_respondidas', models.PositiveIntegerField(default=0, help_text='Número de preguntas respondidas')),
                ('preguntas_revisadas', models.PositiveIntegerField(default=0, help_text='Número de preguntas revisadas')),
                ('alertas_detectadas', models.JSONField(blank=True, default=list, help_text='Lista de alertas detectadas')),
                ('irregularidades', models.TextField(blank=True, help_text='Descripción de irregularidades detectadas')),
                ('motivo_finalizacion', models.TextField(blank=True, help_text='Motivo de la finalización administrativa')),
                ('fecha_finalizacion_admin', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio_monitoreo', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoreos', to='quizzes.evaluacion')),
                ('finalizado_por_admin', models.ForeignKey(blank=True, help_text='Administrador que finalizó la evaluación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_finalizadas', to=settings.AUTH_USER_MODEL)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoreos', to='quizzes.participantes')),
                ('resultado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monitoreo', to='quizzes.resultadoevaluacion')),
            ],
            options={
                'verbose_name': 'Monitoreo de Evaluación',
                'verbose_name_plural': 'Monitoreos de Evaluaciones',
                'ordering': ['-fecha_ultima_actualizacion'],
                'unique_together': {('evaluacion', 'participante')},
            },
        ),
    ]
