# Generated by Django 5.2.4 on 2025-08-02 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0013_monitoreoevaluacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoreoevaluacion',
            name='resultado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoreo', to='quizzes.resultadoevaluacion'),
        ),
    ]
