# Generated by Django 5.2.4 on 2025-08-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0014_alter_monitoreoevaluacion_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantes',
            name='email',
            field=models.EmailField(help_text='Correo electrónico único', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='representante',
            name='CorreoInstitucional',
            field=models.EmailField(help_text='Correo institucional único', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='representante',
            name='CorreoRepresentante',
            field=models.EmailField(help_text='Correo del representante único', max_length=254, unique=True),
        ),
    ]
