# Generated by Django 5.2.4 on 2025-08-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0015_alter_participantes_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudClaveTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Nombre de usuario o cédula del solicitante', max_length=150)),
                ('tipo_usuario', models.CharField(choices=[('admin', 'Administrador'), ('participante', 'Participante')], help_text='Tipo de usuario que solicita', max_length=20)),
                ('email', models.EmailField(help_text='Correo electrónico del usuario', max_length=254)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la solicitud')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP del solicitante', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent del navegador')),
                ('procesada', models.BooleanField(default=False, help_text='Indica si la solicitud fue procesada exitosamente')),
                ('mensaje_error', models.TextField(blank=True, help_text='Mensaje de error si la solicitud falló')),
            ],
            options={
                'verbose_name': 'Solicitud de Clave Temporal',
                'verbose_name_plural': 'Solicitudes de Clave Temporal',
                'ordering': ['-fecha_solicitud'],
                'indexes': [models.Index(fields=['username', 'fecha_solicitud'], name='quizzes_sol_usernam_c07e88_idx'), models.Index(fields=['tipo_usuario', 'fecha_solicitud'], name='quizzes_sol_tipo_us_29dc30_idx')],
            },
        ),
    ]
