# Generated by Django 5.2.4 on 2025-08-04 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0016_solicitudclavetemporal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudclavetemporal',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='solicitudclavetemporal',
            name='user_agent',
        ),
    ]
