# Generated by Django 5.2.4 on 2025-08-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0017_remove_solicitudclavetemporal_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcion',
            name='text',
            field=models.TextField(help_text='Use LaTeX para fórmulas'),
        ),
    ]
