# Generated by Django 5.2.4 on 2025-08-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0018_alter_opcion_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_etapas', models.IntegerField(choices=[(2, 'Dos etapas'), (3, 'Tres etapas')], default=3, help_text='Cantidad de etapas del concurso')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
            },
        ),
    ]
