# Generated by Django 5.2.4 on 2025-08-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0019_systemconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='anio',
            field=models.IntegerField(default=2025, help_text='Año del concurso al que pertenece esta evaluación'),
        ),
        migrations.AddField(
            model_name='grupoparticipantes',
            name='anio',
            field=models.IntegerField(default=2025, help_text='Año del concurso al que pertenece'),
        ),
        migrations.AddField(
            model_name='participantes',
            name='anio',
            field=models.IntegerField(default=2025, help_text='Año del concurso al que pertenece'),
        ),
        migrations.AddField(
            model_name='representante',
            name='anio',
            field=models.IntegerField(default=2025, help_text='Año del concurso al que pertenece'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='active_year',
            field=models.IntegerField(default=2025, help_text='Año activo del concurso'),
        ),
    ]
