# Generated by Django 5.2.4 on 2025-08-13 10:10

import quizzes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0020_evaluacion_anio_grupoparticipantes_anio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantes',
            name='cedula',
            field=models.CharField(max_length=10, validators=[quizzes.models.validate_cedula]),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='email',
            field=models.EmailField(help_text='Correo electrónico (único por año)', max_length=254),
        ),
        migrations.AlterField(
            model_name='representante',
            name='CorreoInstitucional',
            field=models.EmailField(help_text='Correo institucional (único por año)', max_length=254),
        ),
        migrations.AlterField(
            model_name='representante',
            name='CorreoRepresentante',
            field=models.EmailField(help_text='Correo del representante (único por año)', max_length=254),
        ),
        # Nota: los constraints por año de Participantes se agregarán en la migración 0022
        migrations.AddConstraint(
            model_name='representante',
            constraint=models.UniqueConstraint(fields=('CorreoInstitucional', 'anio'), name='unique_correo_institucional_por_anio'),
        ),
        migrations.AddConstraint(
            model_name='representante',
            constraint=models.UniqueConstraint(fields=('CorreoRepresentante', 'anio'), name='unique_correo_representante_por_anio'),
        ),
    ]
