# Generated by Django 5.2.4 on 2025-08-13 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0021_alter_participantes_cedula_alter_participantes_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='participantes',
            constraint=models.UniqueConstraint(fields=('cedula', 'anio'), name='unique_participante_cedula_por_anio'),
        ),
        migrations.AddConstraint(
            model_name='participantes',
            constraint=models.UniqueConstraint(fields=('email', 'anio'), name='unique_participante_email_por_anio'),
        ),
    ]
