# Generated by Django 5.2.4 on 2025-08-13 10:22

import quizzes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0022_remove_evaluacion_unique_participante_cedula_por_anio_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='participantes',
            name='unique_participante_cedula_por_anio',
        ),
        migrations.RemoveConstraint(
            model_name='participantes',
            name='unique_participante_email_por_anio',
        ),
        migrations.RemoveField(
            model_name='participantes',
            name='anio',
        ),
        migrations.AlterField(
            model_name='participantes',
            name='cedula',
            field=models.CharField(max_length=10, unique=True, validators=[quizzes.models.validate_cedula]),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='email',
            field=models.EmailField(help_text='Correo electrónico único', max_length=254, unique=True),
        ),
    ]
