# Generated by Django 5.2.4 on 2025-08-21 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0023_remove_participantes_unique_participante_cedula_por_anio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultadoevaluacion',
            options={'ordering': ['-puntos_obtenidos', 'tiempo_utilizado']},
        ),
        migrations.AlterUniqueTogether(
            name='resultadoevaluacion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='intentos_permitidos_default',
            field=models.PositiveIntegerField(default=1, help_text='Número de intentos permitidos por defecto para todos los participantes'),
        ),
        migrations.AddField(
            model_name='resultadoevaluacion',
            name='es_mejor_intento',
            field=models.BooleanField(default=True, help_text='Indica si este es el mejor intento del participante'),
        ),
        migrations.AddField(
            model_name='resultadoevaluacion',
            name='numero_intento',
            field=models.PositiveIntegerField(default=1, help_text='Número del intento (1, 2, 3, etc.)'),
        ),
        migrations.AlterUniqueTogether(
            name='resultadoevaluacion',
            unique_together={('evaluacion', 'participante', 'numero_intento')},
        ),
        migrations.CreateModel(
            name='IntentoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intentos_permitidos', models.PositiveIntegerField(default=1, help_text='Número de intentos permitidos para este participante en esta evaluación específica')),
                ('intentos_utilizados', models.PositiveIntegerField(default=0, help_text='Número de intentos que ha realizado el participante')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_participantes', to='quizzes.evaluacion')),
                ('modificado_por', models.ForeignKey(blank=True, help_text='Usuario que modificó los intentos de este participante', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_evaluacion', to='quizzes.participantes')),
            ],
            options={
                'verbose_name': 'Intento de Evaluación',
                'verbose_name_plural': 'Intentos de Evaluaciones',
                'unique_together': {('evaluacion', 'participante')},
            },
        ),
    ]
