# Generated by Django 5.2.4 on 2025-08-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0023_remove_participantes_unique_participante_cedula_por_anio_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resultadoevaluacion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='resultadoevaluacion',
            name='numero_intento',
            field=models.PositiveIntegerField(default=1, help_text='Número del intento del participante'),
        ),
        migrations.AlterUniqueTogether(
            name='resultadoevaluacion',
            unique_together={('evaluacion', 'participante', 'numero_intento')},
        ),
    ]
