# Generated by Django 5.2.5 on 2025-08-25 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0024_alter_resultadoevaluacion_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participantes',
            name='intentos_maximos_default',
            field=models.PositiveIntegerField(default=2, help_text='Intentos máximos por defecto para evaluaciones'),
        ),
        migrations.CreateModel(
            name='IntentosParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intentos_maximos', models.PositiveIntegerField(help_text='Intentos máximos para este participante en esta evaluación')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True, help_text='Motivo por el cual se asignaron intentos adicionales')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Admin que asignó los intentos', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_intentos', to='quizzes.evaluacion')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_intentos', to='quizzes.participantes')),
            ],
            options={
                'verbose_name': 'Configuración de Intentos',
                'verbose_name_plural': 'Configuraciones de Intentos',
                'unique_together': {('participante', 'evaluacion')},
            },
        ),
    ]
