# Generated by Django 5.2.5 on 2025-08-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0025_participantes_intentos_maximos_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantes',
            name='intentos_maximos_default',
            field=models.PositiveIntegerField(default=1, help_text='Intentos máximos por defecto para evaluaciones'),
        ),
    ]
