# Generated by Django 5.2.5 on 2025-08-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0026_alter_participantes_intentos_maximos_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoreoevaluacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('activo', 'Activo'), ('inactivo', 'Inactivo'), ('finalizado', 'Finalizado'), ('suspendido', 'Suspendido')], default='pendiente', max_length=20),
        ),
    ]
