# Generated by Django 5.2.5 on 2025-08-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0027_alter_monitoreoevaluacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoreoevaluacion',
            name='alertas',
            field=models.JSONField(blank=True, default=list, help_text='Lista de alertas específicas incluyendo cambios de pestaña'),
        ),
        migrations.AddField(
            model_name='monitoreoevaluacion',
            name='cambios_pestana',
            field=models.PositiveIntegerField(default=0, help_text='Número de cambios de pestaña detectados'),
        ),
        migrations.AddField(
            model_name='resultadoevaluacion',
            name='cambios_pestana',
            field=models.PositiveIntegerField(default=0, help_text='Número de cambios de pestaña durante la evaluación'),
        ),
    ]
