# Generated by Django 5.2.5 on 2025-09-29 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0028_monitoreoevaluacion_alertas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoría (ej: Álgebra, Geometría Analítica)', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional de la categoría')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True, help_text='Si la categoría está activa para su uso')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Categoría temática de la pregunta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas', to='quizzes.categoria'),
        ),
    ]
