# Generated by Django 5.2.4 on 2026-06-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0029_categoria_pregunta_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='anio',
            field=models.IntegerField(default=2026, help_text='Año del concurso al que pertenece esta evaluación'),
        ),
        migrations.AlterField(
            model_name='grupoparticipantes',
            name='anio',
            field=models.IntegerField(default=2026, help_text='Año del concurso al que pertenece'),
        ),
        migrations.AlterField(
            model_name='representante',
            name='anio',
            field=models.IntegerField(default=2026, help_text='Año del concurso al que pertenece'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='active_year',
            field=models.IntegerField(default=2026, help_text='Año activo del concurso'),
        ),
    ]
