# Generated by Django 5.2.4 on 2026-07-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0030_alter_evaluacion_anio_alter_grupoparticipantes_anio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultadoevaluacion',
            options={'ordering': ['-puntos_obtenidos', 'tiempo_utilizado']},
        ),
        migrations.RemoveField(
            model_name='resultadoevaluacion',
            name='puntaje',
        ),
        migrations.AlterField(
            model_name='resultadoevaluacion',
            name='tiempo_utilizado',
            field=models.PositiveIntegerField(default=0, help_text='Tiempo utilizado en segundos'),
        ),
    ]
