# Generated by Django 5.2.4 on 2026-07-25 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0031_alter_resultadoevaluacion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='monitoreoevaluacion',
            name='alertas',
        ),
        migrations.RemoveField(
            model_name='participantes',
            name='password_temporal',
        ),
    ]
