# Generated by Django 5.2.4 on 2026-07-25 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0032_remove_adminprofile_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoevaluacion',
            name='alertas_detectadas',
            field=models.JSONField(blank=True, default=list, help_text='Lista de alertas detectadas durante la prueba'),
        ),
        migrations.AddField(
            model_name='resultadoevaluacion',
            name='fecha_finalizacion_admin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultadoevaluacion',
            name='finalizado_por_admin',
            field=models.ForeignKey(blank=True, help_text='Administrador que finalizó la evaluación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_finalizadas_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultadoevaluacion',
            name='motivo_finalizacion',
            field=models.TextField(blank=True, help_text='Motivo de la finalización administrativa'),
        ),
        migrations.DeleteModel(
            name='MonitoreoEvaluacion',
        ),
    ]
