# Generated by Django 5.2.4 on 2026-07-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0033_resultadoevaluacion_alertas_detectadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='preguntas_dificiles',
            field=models.PositiveIntegerField(default=3, help_text='Cantidad de preguntas difíciles a mostrar (default: 3)'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='preguntas_faciles',
            field=models.PositiveIntegerField(default=4, help_text='Cantidad de preguntas fáciles a mostrar (default: 4)'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='preguntas_medianas',
            field=models.PositiveIntegerField(default=3, help_text='Cantidad de preguntas medias a mostrar (default: 3)'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='dificultad',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Fácil'), (2, 'Media'), (3, 'Difícil')], default=1, help_text='Nivel de dificultad de la pregunta (1=Fácil, 2=Media, 3=Difícil)'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='preguntas_a_mostrar',
            field=models.PositiveIntegerField(default=10, help_text='Número total de preguntas que se mostrarán al estudiante (calculado automáticamente)'),
        ),
    ]
