# Generated by Django 5.2.4 on 2026-07-28 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0034_evaluacion_preguntas_dificiles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadTematica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(help_text='Número de la unidad (1, 2, 3, 4)', unique=True)),
                ('nombre', models.CharField(help_text='Nombre de la unidad temática', max_length=150)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional de la unidad')),
            ],
            options={
                'verbose_name': 'Unidad Temática',
                'verbose_name_plural': 'Unidades Temáticas',
                'ordering': ['numero'],
            },
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='preguntas_unidad_1',
            field=models.PositiveIntegerField(default=4, help_text='Cantidad de preguntas de Unidad 1 a mostrar (default: 4)'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='preguntas_unidad_2',
            field=models.PositiveIntegerField(default=2, help_text='Cantidad de preguntas de Unidad 2 a mostrar (default: 2)'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='preguntas_unidad_3',
            field=models.PositiveIntegerField(default=2, help_text='Cantidad de preguntas de Unidad 3 a mostrar (default: 2)'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='preguntas_unidad_4',
            field=models.PositiveIntegerField(default=2, help_text='Cantidad de preguntas de Unidad 4 a mostrar (default: 2)'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(help_text='Nombre de la categoría (ej: Vectores, Leyes de Newton)', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='unidad',
            field=models.ForeignKey(blank=True, help_text='Unidad temática a la que pertenece la categoría', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias', to='quizzes.unidadtematica'),
        ),
    ]
