# Generated by Django 5.2.4 on 2026-07-28 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0035_unidadtematica_evaluacion_preguntas_unidad_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='preguntas_unidad_1',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='preguntas_unidad_2',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='preguntas_unidad_3',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='preguntas_unidad_4',
        ),
        migrations.AlterField(
            model_name='unidadtematica',
            name='numero',
            field=models.PositiveSmallIntegerField(help_text='Número de la unidad (ej: 1, 2, 3...)', unique=True),
        ),
        migrations.CreateModel(
            name='EvaluacionCuotaUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_preguntas', models.PositiveIntegerField(default=2, help_text='Cantidad de preguntas a seleccionar de esta unidad temática')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas_unidades', to='quizzes.evaluacion')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas_evaluaciones', to='quizzes.unidadtematica')),
            ],
            options={
                'verbose_name': 'Cuota de Unidad Temática',
                'verbose_name_plural': 'Cuotas de Unidades Temáticas',
                'unique_together': {('evaluacion', 'unidad')},
            },
        ),
    ]
