# Generated by Django 5.2.4 on 2026-07-28 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0036_remove_evaluacion_preguntas_unidad_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la Carrera (ej: Ingeniería de Software, Mecánica)', max_length=150)),
                ('codigo', models.CharField(blank=True, max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la Facultad (ej: Facultad de Ciencias de la Ingeniería)', max_length=150, unique=True)),
                ('siglas', models.CharField(blank=True, help_text='Ej: FCI', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='carrera',
            field=models.ForeignKey(blank=True, help_text='Carrera asignada. Si es nulo y tiene acceso_total, es Superadmin global', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administradores', to='quizzes.carrera'),
        ),
        migrations.AddField(
            model_name='participantes',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participantes', to='quizzes.carrera'),
        ),
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del Concurso (ej: I Olimpiada de Física FIC - Febrero 2026)', max_length=200)),
                ('anio', models.IntegerField(default=2026)),
                ('num_etapas', models.PositiveSmallIntegerField(choices=[(2, '2 Etapas'), (3, '3 Etapas')], default=2)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador / Registro'), ('EN_CURSO', 'En Curso'), ('FINALIZADO', 'Finalizado'), ('ARCHIVADO', 'Archivado')], default='BORRADOR', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concursos', to='quizzes.carrera')),
            ],
            options={
                'verbose_name': 'Concurso / Olimpiada',
                'verbose_name_plural': 'Concursos / Olimpiadas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='concurso',
            field=models.ForeignKey(blank=True, help_text='Concurso al que pertenece esta evaluación', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='quizzes.concurso'),
        ),
        migrations.AddField(
            model_name='grupoparticipantes',
            name='concurso',
            field=models.ForeignKey(blank=True, help_text='Concurso específico al que pertenece', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='quizzes.concurso'),
        ),
        migrations.AddField(
            model_name='participantes',
            name='concurso',
            field=models.ForeignKey(blank=True, help_text='Concurso al que pertenece', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='quizzes.concurso'),
        ),
        migrations.AddField(
            model_name='representante',
            name='concurso',
            field=models.ForeignKey(blank=True, help_text='Concurso específico al que pertenece', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representantes', to='quizzes.concurso'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='quizzes.facultad'),
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del tema (ej: Vectores, Leyes de Newton)', max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional del tema')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True, help_text='Si el tema está activo para su uso')),
                ('unidad', models.ForeignKey(blank=True, help_text='Unidad temática a la que pertenece el tema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temas', to='quizzes.unidadtematica')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Categoría temática de la pregunta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas', to='quizzes.tema'),
        ),
        migrations.AlterUniqueTogether(
            name='carrera',
            unique_together={('facultad', 'nombre')},
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
