# Generated by Django 5.2.4 on 2026-08-06 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0037_carrera_facultad_adminprofile_carrera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='acceso_total',
            field=models.BooleanField(default=False, help_text='Permite acceso total a la gestión dentro de su carrera asignada'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='carrera',
            field=models.ForeignKey(blank=True, help_text='Carrera asignada al administrador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administradores', to='quizzes.carrera'),
        ),
    ]
