# Generated by Django 5.2.4 on 2026-08-07 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0038_alter_adminprofile_acceso_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(help_text='Tipo de acción realizada (ej. ELIMINACION_ADMINISTRADOR)', max_length=100)),
                ('detalles', models.TextField(help_text='Detalles completos de la acción y la entidad afectada')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP del cliente', null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del registro')),
                ('usuario_ejecutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
