# Generated by Django 5.2.4 on 2026-08-08 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0039_auditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tema',
            options={'ordering': ['unidad', 'nombre'], 'verbose_name': 'Tema', 'verbose_name_plural': 'Temas'},
        ),
        migrations.AlterModelOptions(
            name='unidadtematica',
            options={'ordering': ['carrera', 'numero'], 'verbose_name': 'Unidad Temática', 'verbose_name_plural': 'Unidades Temáticas'},
        ),
        migrations.AddField(
            model_name='unidadtematica',
            name='carrera',
            field=models.ForeignKey(blank=True, help_text='Carrera a la que pertenece esta unidad temática', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidades_tematicas', to='quizzes.carrera'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='nombre',
            field=models.CharField(help_text='Nombre del tema (ej: Vectores, Leyes de Newton)', max_length=150),
        ),
        migrations.AlterField(
            model_name='unidadtematica',
            name='numero',
            field=models.PositiveSmallIntegerField(help_text='Número de la unidad (ej: 1, 2, 3...)'),
        ),
        migrations.AlterUniqueTogether(
            name='tema',
            unique_together={('unidad', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='unidadtematica',
            unique_together={('carrera', 'numero')},
        ),
    ]
