# Generated by Django 5.2.4 on 2026-08-08 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0040_alter_tema_options_alter_unidadtematica_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadtematica',
            name='carrera',
            field=models.ForeignKey(default=1, help_text='Carrera a la que pertenece esta unidad temática', on_delete=django.db.models.deletion.CASCADE, related_name='unidades_tematicas', to='quizzes.carrera'),
            preserve_default=False,
        ),
    ]
