# Generated by Django 5.2.4 on 2026-08-08 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0041_alter_unidadtematica_carrera'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemConfig',
        ),
    ]
