# Generated by Django 5.2.4 on 2026-08-08 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0042_delete_systemconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='concurso',
            field=models.ForeignKey(default=1, help_text='Concurso al que pertenece esta evaluación', on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='quizzes.concurso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grupoparticipantes',
            name='concurso',
            field=models.ForeignKey(default=1, help_text='Concurso específico al que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='quizzes.concurso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participantes',
            name='carrera',
            field=models.ForeignKey(default=1, help_text='Carrera a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='quizzes.carrera'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participantes',
            name='concurso',
            field=models.ForeignKey(default=1, help_text='Concurso al que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='quizzes.concurso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='categoria',
            field=models.ForeignKey(default=1, help_text='Categoría temática de la pregunta', on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='quizzes.tema'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='representante',
            name='concurso',
            field=models.ForeignKey(default=1, help_text='Concurso específico al que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='representantes', to='quizzes.concurso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tema',
            name='unidad',
            field=models.ForeignKey(default=1, help_text='Unidad temática a la que pertenece el tema', on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='quizzes.unidadtematica'),
            preserve_default=False,
        ),
    ]
