# Generated by Django 5.2.4 on 2026-08-10 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0043_alter_evaluacion_concurso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='preguntas_dificiles',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='preguntas_faciles',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='preguntas_medianas',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='dificultad',
        ),
    ]
