# Generated by Django 5.2.4 on 2026-08-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0044_remove_evaluacion_preguntas_dificiles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='preguntas_a_mostrar',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Número total de preguntas que se mostrarán al estudiante (calculado automáticamente al configurar cuotas)', null=True),
        ),
    ]
